import assert from 'node:assert/strict';
import test from 'node:test';
import { sha256 } from '../../src/crypto.js';
import { IntegrityError } from '../../src/errors.js';
import { buildSyntheticRendition, parseAndVerifyManifest } from '../../src/segmenter.js';

function generator(seed) {
  let state = seed >>> 0;
  return () => {
    state = (Math.imul(state, 1_664_525) + 1_013_904_223) >>> 0;
    return state;
  };
}

test('synthetic segmentation is deterministic, ordered, and lossless', () => {
  const source = Buffer.alloc(3_075, 9);
  const first = buildSyntheticRendition(source, { segmentBytes: 1_024 });
  const second = buildSyntheticRendition(Buffer.from(source), { segmentBytes: 1_024 });
  assert.deepEqual(first.manifest, second.manifest);
  assert.equal(first.manifestSha256, second.manifestSha256);
  assert.ok(Buffer.concat(first.segments.map((segment) => segment.bytes)).equals(source));
  assert.deepEqual(first.segments.map((segment) => segment.size), [1_024, 1_024, 1_024, 3]);
  assert.deepEqual(first.segments.map((segment) => segment.index), [0, 1, 2, 3]);
  assert.deepEqual(parseAndVerifyManifest(first.manifestBytes, first.manifestSha256), first.manifest);
});

test('generated byte corpora preserve coverage, digest, bounds, and canonical manifests', () => {
  const next = generator(14_2026);
  const segmentSizes = [1_024, 4_096, 65_536];
  for (let trial = 0; trial < 120; trial += 1) {
    const size = 1 + (next() % 180_000);
    const source = Buffer.allocUnsafe(size);
    for (let index = 0; index < size; index += 1) source[index] = next() & 0xff;
    const segmentBytes = segmentSizes[next() % segmentSizes.length];
    const artifact = buildSyntheticRendition(source, { segmentBytes });
    assert.ok(Buffer.concat(artifact.segments.map((segment) => segment.bytes)).equals(source));
    assert.equal(artifact.manifest.sourceSha256, sha256(source));
    assert.equal(artifact.manifest.totalBytes, size);
    assert.ok(artifact.segments.every((segment) => segment.size > 0 && segment.size <= segmentBytes));
    assert.ok(artifact.segments.every((segment) => sha256(segment.bytes) === segment.sha256));
    assert.equal(sha256(artifact.manifestBytes), artifact.manifestSha256);
    assert.deepEqual(parseAndVerifyManifest(artifact.manifestBytes, artifact.manifestSha256), artifact.manifest);
  }
});

test('manifest parsing rejects changed bytes and non-canonical content', () => {
  const artifact = buildSyntheticRendition(Buffer.alloc(2_048, 7), { segmentBytes: 1_024 });
  const changed = Buffer.from(artifact.manifestBytes);
  changed[changed.length - 2] ^= 1;
  assert.throws(() => parseAndVerifyManifest(changed, artifact.manifestSha256), IntegrityError);
  const spaced = Buffer.from(`${JSON.stringify(artifact.manifest, null, 2)}\n`);
  assert.throws(() => parseAndVerifyManifest(spaced, sha256(spaced)), IntegrityError);
  const redistributed = structuredClone(artifact.manifest);
  redistributed.segments[0].bytes -= 1;
  redistributed.segments[1].bytes += 1;
  const redistributedBytes = Buffer.from(JSON.stringify(redistributed));
  assert.throws(() => parseAndVerifyManifest(redistributedBytes, sha256(redistributedBytes)), IntegrityError);
});
